# Generated by Django 5.2.10 on 2026-01-30 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Superseded by 0003_combined.py - kept as a no-op to avoid conflicts."""

    dependencies = [
        ('app', '0002_new_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No operations - merged into 0003_combined
    ]
