# Generated by merge on 2026-01-31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_new_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # From 0003_medicinecategory_medicine_brand_name_and_more
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='condition',
            field=models.CharField(choices=[('new', 'New/Sealed'), ('opened', 'Opened but Unused'), ('partial', 'Partially Used'), ('unknown', 'Unknown')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pickup_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('donated', 'Donated'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('quality_check', 'Quality Check'), ('distributed', 'Distributed')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partial', 'Partially Fulfilled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(default='units', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('patient_count', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinecategory')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkDonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(default='units', max_length=20)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fulfilled_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bulk_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.bulkdonationrequest')),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinecategory')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='app.medicinecategory'),
        ),
        migrations.CreateModel(
            name='MedicineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('total_medicines_donated', models.IntegerField(default=0)),
                ('total_donors', models.IntegerField(default=0)),
                ('total_ngos', models.IntegerField(default=0)),
                ('total_requests_fulfilled', models.IntegerField(default=0)),
                ('medicines_by_category', models.JSONField(default=dict)),
                ('top_donors', models.JSONField(default=list)),
                ('top_ngos', models.JSONField(default=list)),
                ('emergency_alerts_created', models.IntegerField(default=0)),
                ('emergency_alerts_resolved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-quarter'],
                'unique_together': {('report_type', 'year', 'month', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='MedicineSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.medicinecategory')),
            ],
            options={
                'verbose_name_plural': 'Medicine Subcategories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='app.medicinesubcategory'),
        ),
        migrations.CreateModel(
            name='MedicineVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'More Info Required')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='app.medicine')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('donate', 'Donate'), ('request', 'Request'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='app_auditlo_user_id_d511bf_idx'), models.Index(fields=['model_name', 'object_id'], name='app_auditlo_model_n_9aa5af_idx'), models.Index(fields=['timestamp'], name='app_auditlo_timesta_90fa40_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock_level', models.IntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('auto_reorder', models.BooleanField(default=False)),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinecategory')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ngo', 'medicine_category', 'medicine_name')},
            },
        ),
        # From 0003_pickupdelivery
        migrations.CreateModel(
            name='PickupDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('quantity_scheduled', models.IntegerField()),
                ('quantity_picked_up', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_delivered', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_delivery', to='app.donationrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups_given', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='app.medicine')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
