# Generated by Django 5.2.10 on 2026-01-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicinecategory_medicine_brand_name_and_more'),
        ('app', '0003_pickupdelivery'),
        ('app', '0005_merge_20260130_2343'),
    ]

    operations = [
    ]
