# Generated by Django 5.2.7 on 2026-02-01 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_location_latitude_message_location_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='ngo',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='requester_type',
            field=models.CharField(choices=[('ngo', 'NGO'), ('individual', 'Individual')], default='individual', max_length=20),
        ),
    ]
