# Generated by Django 5.2.7 on 2026-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_donationrequest_ngo_donationrequest_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='location_confidence',
            field=models.CharField(blank=True, help_text="Confidence of location: 'high', 'low', or 'unknown'.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_confidence',
            field=models.CharField(blank=True, help_text="Confidence of location: 'high', 'low', or 'unknown'.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('unable_to_pickup', 'Unable to Pickup'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
