# Generated by Django 5.2.10 on 2026-02-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emergencyalertresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrequest',
            options={},
        ),
    ]
