# Generated by Django 5.2.10 on 2026-02-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_porterpartner_deliveryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='medicinereport',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='medicinereport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='message',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='message',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereport',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
        migrations.RemoveField(
            model_name='medicinereport',
            name='emergency_alerts_created',
        ),
        migrations.RemoveField(
            model_name='medicinereport',
            name='emergency_alerts_resolved',
        ),
        migrations.RemoveField(
            model_name='medicinereport',
            name='top_ngos',
        ),
    ]
