# Generated by Django 5.2.10 on 2026-02-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_deliverylocation_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('location', 'Location'), ('location_request', 'Location Request')], default='text', max_length=20),
        ),
    ]
