# Generated by Django 5.2.10 on 2026-02-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
