from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from app.models import Medicine, MedicineCategory, MedicineSubcategory
from datetime import datetime, timedelta
from django.utils import timezone


class Command(BaseCommand):
    help = 'Create 20 realistic medicines with complete data'

    def handle(self, *args, **options):
        # Get or create categories
        antibiotics_cat, _ = MedicineCategory.objects.get_or_create(
            name='Antibiotics',
            defaults={'description': 'Antibacterial medicines', 'icon': 'fa-pills', 'color': '#FF6B6B'}
        )
        
        painkillers_cat, _ = MedicineCategory.objects.get_or_create(
            name='Pain Relief',
            defaults={'description': 'Pain and fever management', 'icon': 'fa-heart', 'color': '#FF9FF3'}
        )
        
        respiratory_cat, _ = MedicineCategory.objects.get_or_create(
            name='Respiratory',
            defaults={'description': 'Cold, cough and respiratory', 'icon': 'fa-lungs', 'color': '#74B9FF'}
        )
        
        vitamins_cat, _ = MedicineCategory.objects.get_or_create(
            name='Vitamins & Supplements',
            defaults={'description': 'Vitamins and nutritional supplements', 'icon': 'fa-apple-alt', 'color': '#A29BFE'}
        )
        
        digestive_cat, _ = MedicineCategory.objects.get_or_create(
            name='Digestive Health',
            defaults={'description': 'Digestive and gastrointestinal', 'icon': 'fa-beer', 'color': '#FDCB6E'}
        )
        
        # Create subcategories
        amoxicillin_sub, _ = MedicineSubcategory.objects.get_or_create(
            category=antibiotics_cat,
            name='Penicillin Based',
            defaults={'description': 'Penicillin derivative antibiotics'}
        )
        
        fever_sub, _ = MedicineSubcategory.objects.get_or_create(
            category=painkillers_cat,
            name='Fever & Pain',
            defaults={'description': 'Antipyretic and analgesic'}
        )
        
        cough_sub, _ = MedicineSubcategory.objects.get_or_create(
            category=respiratory_cat,
            name='Cough Syrup',
            defaults={'description': 'Cough suppressant and expectorant'}
        )
        
        # Get donors
        donors = list(User.objects.filter(profile__role='donor')[:5])
        
        if not donors:
            self.stdout.write(self.style.ERROR('No donors found. Please create donors first.'))
            return
        
        # Medicine data
        medicines_data = [
            {
                'name': 'Amoxicillin 500mg',
                'generic_name': 'Amoxicillin',
                'brand_name': 'Amoxil',
                'category': antibiotics_cat,
                'subcategory': amoxicillin_sub,
                'description': 'Penicillin-type antibiotic used to treat bacterial infections',
                'composition': 'Amoxicillin trihydrate 500mg',
                'dosage_form': 'Tablet',
                'strength': '500mg',
                'quantity': 30,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Glaxo SmithKline',
                'batch_number': 'GSK2024001',
                'storage_condition': 'Store below 25°C, dry place',
                'usage_instructions': 'Take 1 tablet thrice daily for 7 days with water',
                'side_effects': 'Nausea, diarrhea, allergic reactions',
                'prescription_required': True,
                'donor_index': 0,
                'latitude': 28.6139,
                'longitude': 77.2090,
                'location_name': 'Delhi',
            },
            {
                'name': 'Paracetamol 650mg',
                'generic_name': 'Paracetamol',
                'brand_name': 'Crocin',
                'category': painkillers_cat,
                'subcategory': fever_sub,
                'description': 'Fever and pain reliever',
                'composition': 'Paracetamol 650mg',
                'dosage_form': 'Tablet',
                'strength': '650mg',
                'quantity': 50,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Cipla Ltd',
                'batch_number': 'CIP2024045',
                'storage_condition': 'Store at room temperature',
                'usage_instructions': 'Take 1 tablet every 4-6 hours as needed',
                'side_effects': 'Rare: liver toxicity if overdosed',
                'prescription_required': False,
                'donor_index': 1,
                'latitude': 19.0760,
                'longitude': 72.8777,
                'location_name': 'Mumbai',
            },
            {
                'name': 'Ibuprofen 400mg',
                'generic_name': 'Ibuprofen',
                'brand_name': 'Brufen',
                'category': painkillers_cat,
                'subcategory': fever_sub,
                'description': 'Anti-inflammatory pain reliever',
                'composition': 'Ibuprofen 400mg',
                'dosage_form': 'Tablet',
                'strength': '400mg',
                'quantity': 20,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Abbott Healthcare',
                'batch_number': 'ABB2024089',
                'storage_condition': 'Cool, dry place',
                'usage_instructions': 'Take with food, 1 tablet every 6-8 hours',
                'side_effects': 'Stomach upset, headache',
                'prescription_required': False,
                'donor_index': 2,
                'latitude': 12.9716,
                'longitude': 77.5946,
                'location_name': 'Bengaluru',
            },
            {
                'name': 'Cough Syrup DXM 10mg',
                'generic_name': 'Dextromethorphan',
                'brand_name': 'Coughex',
                'category': respiratory_cat,
                'subcategory': cough_sub,
                'description': 'Cough suppressant syrup',
                'composition': 'Dextromethorphan 10mg/5ml',
                'dosage_form': 'Syrup',
                'strength': '10mg/5ml',
                'quantity': 100,
                'unit': 'ml',
                'condition': 'new',
                'manufacturer': 'Cipla Ltd',
                'batch_number': 'CIP2024056',
                'storage_condition': 'Shake well before use, store below 30°C',
                'usage_instructions': '2 teaspoons thrice daily',
                'side_effects': 'Drowsiness, dizziness',
                'prescription_required': False,
                'donor_index': 3,
                'latitude': 23.1815,
                'longitude': 79.9864,
                'location_name': 'Indore',
            },
            {
                'name': 'Vitamin C 500mg',
                'generic_name': 'Ascorbic Acid',
                'brand_name': 'Limcee',
                'category': vitamins_cat,
                'subcategory': None,
                'description': 'Immune booster vitamin supplement',
                'composition': 'Ascorbic Acid 500mg',
                'dosage_form': 'Tablet',
                'strength': '500mg',
                'quantity': 60,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Abbott India',
                'batch_number': 'ABB2024123',
                'storage_condition': 'Store in cool dry place',
                'usage_instructions': '1 tablet daily after breakfast',
                'side_effects': 'None significant',
                'prescription_required': False,
                'donor_index': 0,
                'latitude': 28.6139,
                'longitude': 77.2090,
                'location_name': 'Delhi',
            },
            {
                'name': 'Ciprofloxacin 500mg',
                'generic_name': 'Ciprofloxacin',
                'brand_name': 'Ciproquin',
                'category': antibiotics_cat,
                'subcategory': None,
                'description': 'Broad spectrum fluoroquinolone antibiotic',
                'composition': 'Ciprofloxacin 500mg',
                'dosage_form': 'Tablet',
                'strength': '500mg',
                'quantity': 10,
                'unit': 'tablets',
                'condition': 'opened',
                'manufacturer': 'Cipla Ltd',
                'batch_number': 'CIP2024012',
                'storage_condition': 'Room temperature, protect from light',
                'usage_instructions': '1 tablet twice daily for 3-5 days',
                'side_effects': 'Tendon rupture (rare), QT prolongation',
                'prescription_required': True,
                'donor_index': 1,
                'latitude': 19.0760,
                'longitude': 72.8777,
                'location_name': 'Mumbai',
            },
            {
                'name': 'Omeprazole 20mg',
                'generic_name': 'Omeprazole',
                'brand_name': 'Omez',
                'category': digestive_cat,
                'subcategory': None,
                'description': 'Proton pump inhibitor for acid reflux',
                'composition': 'Omeprazole 20mg',
                'dosage_form': 'Capsule',
                'strength': '20mg',
                'quantity': 14,
                'unit': 'capsules',
                'condition': 'new',
                'manufacturer': 'Dr Reddys Labs',
                'batch_number': 'DRL2024078',
                'storage_condition': 'Below 25°C, away from moisture',
                'usage_instructions': '1 capsule daily 30 minutes before breakfast',
                'side_effects': 'Headache, nausea',
                'prescription_required': True,
                'donor_index': 2,
                'latitude': 12.9716,
                'longitude': 77.5946,
                'location_name': 'Bengaluru',
            },
            {
                'name': 'Metformin 500mg',
                'generic_name': 'Metformin',
                'brand_name': 'Glucophage',
                'category': vitamins_cat,
                'subcategory': None,
                'description': 'Diabetes management medication',
                'composition': 'Metformin Hydrochloride 500mg',
                'dosage_form': 'Tablet',
                'strength': '500mg',
                'quantity': 30,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Bristol Myers Squibb',
                'batch_number': 'BMS2024045',
                'storage_condition': 'Room temperature, dry place',
                'usage_instructions': '1 tablet thrice daily with meals',
                'side_effects': 'Lactic acidosis (rare), GI upset',
                'prescription_required': True,
                'donor_index': 3,
                'latitude': 23.1815,
                'longitude': 79.9864,
                'location_name': 'Indore',
            },
            {
                'name': 'Aspirin 75mg',
                'generic_name': 'Acetylsalicylic Acid',
                'brand_name': 'Ecosprin',
                'category': painkillers_cat,
                'subcategory': fever_sub,
                'description': 'Cardiovascular protective aspirin',
                'composition': 'Acetylsalicylic Acid 75mg',
                'dosage_form': 'Tablet',
                'strength': '75mg',
                'quantity': 100,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Micro Labs',
                'batch_number': 'MCL2024056',
                'storage_condition': 'Dry place, below 25°C',
                'usage_instructions': '1 tablet daily after breakfast',
                'side_effects': 'Gastrointestinal bleeding (rare)',
                'prescription_required': True,
                'donor_index': 4,
                'latitude': 21.1458,
                'longitude': 79.0882,
                'location_name': 'Nagpur',
            },
            {
                'name': 'Antibacterial Cream 30g',
                'generic_name': 'Neomycin + Bacitracin',
                'brand_name': 'Sofraderm',
                'category': antibiotics_cat,
                'subcategory': None,
                'description': 'Topical antibiotic cream for wounds',
                'composition': 'Neomycin 500U/g, Bacitracin 400U/g',
                'dosage_form': 'Cream',
                'strength': '30g',
                'quantity': 2,
                'unit': 'tubes',
                'condition': 'new',
                'manufacturer': 'Glaxo SmithKline',
                'batch_number': 'GSK2024089',
                'storage_condition': 'Below 25°C, away from moisture',
                'usage_instructions': 'Apply thin layer 2-3 times daily on clean wound',
                'side_effects': 'Local allergic reactions',
                'prescription_required': False,
                'donor_index': 0,
                'latitude': 28.6139,
                'longitude': 77.2090,
                'location_name': 'Delhi',
            },
            {
                'name': 'Multivitamin Syrup 200ml',
                'generic_name': 'Vitamin A, B, C, D, E Complex',
                'brand_name': 'Polybion',
                'category': vitamins_cat,
                'subcategory': None,
                'description': 'Complete multivitamin syrup for children',
                'composition': 'Vitamins A 5000IU, B1 1.5mg, B2 1.7mg, C 50mg, D 400IU, E 10IU per 5ml',
                'dosage_form': 'Syrup',
                'strength': '200ml',
                'quantity': 1,
                'unit': 'bottle',
                'condition': 'opened',
                'manufacturer': 'Abbott India',
                'batch_number': 'ABB2024067',
                'storage_condition': 'Shake well, below 30°C',
                'usage_instructions': '1 teaspoon twice daily with meals',
                'side_effects': 'Rare allergic reactions',
                'prescription_required': False,
                'donor_index': 1,
                'latitude': 19.0760,
                'longitude': 72.8777,
                'location_name': 'Mumbai',
            },
            {
                'name': 'Antihistamine Tablet 10mg',
                'generic_name': 'Cetirizine',
                'brand_name': 'Alzental',
                'category': respiratory_cat,
                'subcategory': None,
                'description': 'Non-drowsy antihistamine for allergies',
                'composition': 'Cetirizine Hydrochloride 10mg',
                'dosage_form': 'Tablet',
                'strength': '10mg',
                'quantity': 30,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Cipla Ltd',
                'batch_number': 'CIP2024034',
                'storage_condition': 'Room temperature',
                'usage_instructions': '1 tablet once daily in evening',
                'side_effects': 'Minimal side effects',
                'prescription_required': False,
                'donor_index': 2,
                'latitude': 12.9716,
                'longitude': 77.5946,
                'location_name': 'Bengaluru',
            },
            {
                'name': 'Antibiotic Eye Drops 10ml',
                'generic_name': 'Chloramphenicol',
                'brand_name': 'Chloromycetin',
                'category': antibiotics_cat,
                'subcategory': None,
                'description': 'Broad spectrum antibiotic eye drops',
                'composition': 'Chloramphenicol 0.5%',
                'dosage_form': 'Eye Drops',
                'strength': '10ml',
                'quantity': 1,
                'unit': 'bottle',
                'condition': 'new',
                'manufacturer': 'Parke Davis',
                'batch_number': 'PD2024023',
                'storage_condition': 'Refrigerate after opening, use within 4 weeks',
                'usage_instructions': '1-2 drops every 2-4 hours',
                'side_effects': 'Stinging, local irritation',
                'prescription_required': True,
                'donor_index': 3,
                'latitude': 23.1815,
                'longitude': 79.9864,
                'location_name': 'Indore',
            },
            {
                'name': 'Antacid Suspension 200ml',
                'generic_name': 'Magnesium Hydroxide + Aluminum Hydroxide',
                'brand_name': 'Gelusil',
                'category': digestive_cat,
                'subcategory': None,
                'description': 'Quick relief from acidity and indigestion',
                'composition': 'Magnesium Hydroxide 200mg, Aluminum Hydroxide 200mg per 5ml',
                'dosage_form': 'Suspension',
                'strength': '200ml',
                'quantity': 1,
                'unit': 'bottle',
                'condition': 'new',
                'manufacturer': 'GlaxoSmithKline',
                'batch_number': 'GSK2024091',
                'storage_condition': 'Shake well before use, room temperature',
                'usage_instructions': '2-4 teaspoons 3-4 times daily or as directed',
                'side_effects': 'Constipation, diarrhea',
                'prescription_required': False,
                'donor_index': 4,
                'latitude': 21.1458,
                'longitude': 79.0882,
                'location_name': 'Nagpur',
            },
            {
                'name': 'Iron Supplement 65mg',
                'generic_name': 'Ferrous Sulphate',
                'brand_name': 'Feroglobin',
                'category': vitamins_cat,
                'subcategory': None,
                'description': 'Iron supplement for anemia',
                'composition': 'Ferrous Sulphate 65mg (equivalent to 20mg iron)',
                'dosage_form': 'Tablet',
                'strength': '65mg',
                'quantity': 30,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Glaxo SmithKline',
                'batch_number': 'GSK2024102',
                'storage_condition': 'Room temperature, dry place',
                'usage_instructions': '1 tablet once daily with orange juice',
                'side_effects': 'Black stools, constipation, nausea',
                'prescription_required': True,
                'donor_index': 0,
                'latitude': 28.6139,
                'longitude': 77.2090,
                'location_name': 'Delhi',
            },
            {
                'name': 'Antibiotic Ointment 20g',
                'generic_name': 'Mupirocin',
                'brand_name': 'Bactroban',
                'category': antibiotics_cat,
                'subcategory': None,
                'description': 'Topical antibiotic for skin infections',
                'composition': 'Mupirocin 2%',
                'dosage_form': 'Ointment',
                'strength': '20g',
                'quantity': 1,
                'unit': 'tube',
                'condition': 'new',
                'manufacturer': 'GlaxoSmithKline',
                'batch_number': 'GSK2024055',
                'storage_condition': 'Below 25°C',
                'usage_instructions': 'Apply small amount 2-3 times daily on infection',
                'side_effects': 'Local irritation, dermatitis',
                'prescription_required': True,
                'donor_index': 1,
                'latitude': 19.0760,
                'longitude': 72.8777,
                'location_name': 'Mumbai',
            },
            {
                'name': 'Antispasmodic Tablet 20mg',
                'generic_name': 'Dicyclomine',
                'brand_name': 'Dispacid',
                'category': digestive_cat,
                'subcategory': None,
                'description': 'Relief from abdominal cramps and spasms',
                'composition': 'Dicyclomine Hydrochloride 20mg',
                'dosage_form': 'Tablet',
                'strength': '20mg',
                'quantity': 20,
                'unit': 'tablets',
                'condition': 'partial',
                'manufacturer': 'Abbott India',
                'batch_number': 'ABB2024087',
                'storage_condition': 'Room temperature',
                'usage_instructions': '1 tablet thrice daily as needed',
                'side_effects': 'Dry mouth, dizziness, drowsiness',
                'prescription_required': True,
                'donor_index': 2,
                'latitude': 12.9716,
                'longitude': 77.5946,
                'location_name': 'Bengaluru',
            },
            {
                'name': 'Allergy Relief Syrup 100ml',
                'generic_name': 'Pheniramine Maleate',
                'brand_name': 'Avil',
                'category': respiratory_cat,
                'subcategory': None,
                'description': 'Allergy and urticaria relief syrup',
                'composition': 'Pheniramine Maleate 2mg per 5ml',
                'dosage_form': 'Syrup',
                'strength': '100ml',
                'quantity': 1,
                'unit': 'bottle',
                'condition': 'new',
                'manufacturer': 'Cipla Ltd',
                'batch_number': 'CIP2024064',
                'storage_condition': 'Below 30°C, shake well',
                'usage_instructions': '2 teaspoons 2-3 times daily',
                'side_effects': 'Drowsiness, dry mouth',
                'prescription_required': False,
                'donor_index': 3,
                'latitude': 23.1815,
                'longitude': 79.9864,
                'location_name': 'Indore',
            },
            {
                'name': 'Calcium Supplement 500mg',
                'generic_name': 'Calcium Carbonate',
                'brand_name': 'Shelcal',
                'category': vitamins_cat,
                'subcategory': None,
                'description': 'Bone health and calcium supplement',
                'composition': 'Calcium Carbonate 500mg + Vitamin D3 200IU',
                'dosage_form': 'Tablet',
                'strength': '500mg',
                'quantity': 60,
                'unit': 'tablets',
                'condition': 'new',
                'manufacturer': 'Torrent Pharma',
                'batch_number': 'TOR2024072',
                'storage_condition': 'Dry place, room temperature',
                'usage_instructions': '1 tablet twice daily after meals',
                'side_effects': 'Constipation, bloating',
                'prescription_required': False,
                'donor_index': 4,
                'latitude': 21.1458,
                'longitude': 79.0882,
                'location_name': 'Nagpur',
            },
        ]
        
        self.stdout.write(self.style.SUCCESS('\n' + '='*70))
        self.stdout.write(self.style.SUCCESS('Creating 20 Realistic Medicines'))
        self.stdout.write(self.style.SUCCESS('='*70))
        
        created_count = 0
        expiry_date = timezone.now().date() + timedelta(days=180)
        manufacture_date = timezone.now().date() - timedelta(days=90)
        
        for med_data in medicines_data:
            try:
                donor = donors[med_data.pop('donor_index')]
                
                medicine, created = Medicine.objects.get_or_create(
                    donor=donor,
                    name=med_data['name'],
                    defaults={
                        **med_data,
                        'expiry_date': expiry_date,
                        'manufacture_date': manufacture_date,
                        'status': 'available',
                        'verified_by_admin': True,
                        'rating': 4.5,
                        'rating_count': 15,
                    }
                )
                
                if created:
                    self.stdout.write(
                        self.style.SUCCESS(f'✓ Created: {medicine.name}')
                    )
                    self.stdout.write(f'  Brand: {medicine.brand_name} | Quantity: {medicine.quantity} {medicine.unit}')
                    self.stdout.write(f'  Donor: {donor.username} | Expiry: {medicine.expiry_date}')
                    created_count += 1
                else:
                    self.stdout.write(
                        self.style.WARNING(f'✗ Already exists: {medicine.name}')
                    )
            
            except Exception as e:
                self.stdout.write(
                    self.style.ERROR(f'✗ Error creating {med_data.get("name")}: {str(e)}')
                )
        
        self.stdout.write(self.style.SUCCESS('\n' + '='*70))
        self.stdout.write(self.style.SUCCESS(f'✓ Successfully created {created_count} medicines!'))
        self.stdout.write(self.style.SUCCESS('='*70 + '\n'))
